### ISSUE TITLE
[BUG] Server URL too turncated 

### ISSUE THREAD

**Issue by Generator** [JGeek00/adguard-home-manager#10]
## Description 
Long server URL only shows protocol
![Screenshot_20221019-141037_AdGuard Home Manager](https://user-images.githubusercontent.com/44146/196704726-4e37aa6a-213b-4248-8115-171fe1cd2b2b.png)

**Comment by JGeek00** [comment]
I will check it.

**Comment by JGeek00** [comment]
Fixed on v0.10.1
