### ISSUE TITLE
Add ...

### ISSUE THREAD

**Issue by stablelover0** [JGeek00/adguard-home-manager#101]
![Screenshot_20231211-015012_Brave.jpg](https://github.com/JGeek00/adguard-home-manager/assets/75412448/06b206b9-c620-4998-b9e5-7befbdfcb29d)

I don't know how to explain it exactly. The summary that comes up when you click on the eye button.

**Comment by JGeek00** [comment]
I cannot add that because that info doesn't come from the API

**Comment by stablelover0** [comment]
> I cannot add that because that info doesn't come from the API

Ok then. It seems like there are no more features to add :D good luck man
