### ISSUE TITLE
Add statistics configuration option 

### ISSUE THREAD

**Issue by stablelover0** [JGeek00/adguard-home-manager#104]
![Ekran Görüntüsü (58)](https://github.com/JGeek00/adguard-home-manager/assets/75412448/062a883d-10b2-44dc-aab8-ddbe5c0cbcdd)

**Comment by JGeek00** [comment]
That feature is already on the app. You can find it by tapping on the gear icon on the logs screen. The ignored domains field is missing.

**Comment by stablelover0** [comment]
> That feature is already on the app. You can find it by tapping on the gear icon on the logs screen. The ignored domains field is missing.

Logs setting is not the same as this setting, check it on adguard home. I think their functions are different

**Comment by stablelover0** [comment]
There are 2 options, log and statistics settings. Log settings available within the application. But statistics not

**Comment by JGeek00** [comment]
hmmmm yes, I missed that new section
