### ISSUE TITLE
Show device client names

### ISSUE THREAD

**Issue by Generator** [JGeek00/adguard-home-manager#11]
## Description
Show client names like on AdGuard Home dashboard for easier identification

'AdGuard Home Manager'
![Screenshot_20221019-141103_AdGuard Home Manager](https://user-images.githubusercontent.com/44146/196706002-cbe7630a-fd60-4009-9eb3-ab91eebf7581.png)

'AdGuard Home' Dashboard
![Screenshot 2022-10-19 at 14-35-21 AdGuard Home](https://user-images.githubusercontent.com/44146/196706525-ed7271eb-dc5a-4ab0-ad5e-dfa85c0adf0e.png)

**Comment by JGeek00** [comment]
Ok. I note it. Probably I will come to this when the app ends it's beta period, as part of the following updates with improvements.

**Comment by JGeek00** [comment]
Added on v0.10.2
