### ISSUE TITLE
Cant connect to the server locally using the IP address

### ISSUE THREAD

**Issue by tOOmki** [JGeek00/adguard-home-manager#110]
I cannot connect to the server locally using the IP address.
However, over domain connection works.
The domain is added to Nginx Proxy Manager where the IP address of the AGH server is indicated.

Only "Unknown error" message appears
I checked on 2 phones - the same

**Comment by JGeek00** [comment]
Make sure that the url that appears at the top of the connection form matches exactly what you input on your browser to access the admin panel. If you are connecting using HTTPS make sure to enable Override SSL validation on Settings > Advanced settings.

**Comment by tOOmki** [comment]
If I turn off encryption, it works over http.
When I turn on encryption, it doesn't work over https.
I tried the "Dont check SSL certificate" option and it doesn't work.

It worked after disabling "Automatically redirect to HTTPS" in option AGH

**Comment by JGeek00** [comment]
I have investigated it, and if you have the redirect option enabled on AGH you must select HTTPS and use the HTTPS port instead of the HTTP port.

**Comment by ltkun** [comment]
Same problem when using IP.
