### ISSUE TITLE
Privacy Policy Clarification

### ISSUE THREAD

**Issue by phoropter** [JGeek00/adguard-home-manager#111]
Hi, 

Can you clarify

> Under ANY CIRCUNSTANCE there will be captured user's personal information such as emails, usernames, passwords, geolocation, carrier info, phone number, installed apps or any other information that could be used to track an user on the Internet or to create a virtual profile of a single user or a group of users.

I think there might be a typo? Or are you saying all of this will be captured?

**Comment by JGeek00** [comment]
I mean that such information never is captured.

**Comment by phoropter** [comment]
Ah that's good, so it should say

> Under NO CIRCUMSTANCE will there be captured user's personal information such as emails, usernames, passwords, geolocation, carrier info, phone number, installed apps or any other information that could be used to track an user on the Internet or to create a virtual profile of a single user or a group of users.

**Comment by JGeek00** [comment]
Ok, I will change it. I'm Spanish and my English is not the best.

**Comment by phoropter** [comment]
No worries! Thank you for your quick response!

**Comment by JGeek00** [comment]
You're welcome. I hope you enjoy the app.
