### ISSUE TITLE
Saving issue with backup DNS servers setting

### ISSUE THREAD

**Issue by winzortdusmani** [JGeek00/adguard-home-manager#113]
It is not possible to leave this field empty in the application, I cannot save it when it is removed as shown in the video. When I do not write the DNS address in it, it gives an "Invalid ip address" warning.

https://github.com/JGeek00/adguard-home-manager/assets/75412448/4c77d4d7-63e4-4494-a106-3767c8363a16

**Comment by JGeek00** [comment]
Fixed on v2.14.1.
