### ISSUE TITLE
Customization settings issue (PC)

### ISSUE THREAD

**Issue by winzortdusmani** [JGeek00/adguard-home-manager#117]
![Ekran Görüntüsü (120)](https://github.com/JGeek00/adguard-home-manager/assets/75412448/0f70e35f-4378-421d-8a32-a9715aa0d564)

**Comment by JGeek00** [comment]
You mean that there is no scroll bar right?

**Comment by winzortdusmani** [comment]
> You mean that there is no scroll bar right?

Actually, the colors fit there perfectly, half of the blue button is not visible in the photo, try.

**Comment by winzortdusmani** [comment]
> > You mean that there is no scroll bar right?
> 
> Actually, the colors fit there perfectly, half of the blue button is not visible in the app, try.

**Comment by winzortdusmani** [comment]
You can make the buttons a little smaller to fit perfectly there. The rest is up to you

**Comment by JGeek00** [comment]
Fixed on v2.15.0-beta.1.
