### ISSUE TITLE
Client names

### ISSUE THREAD

**Issue by winzortdusmani** [JGeek00/adguard-home-manager#118]
![Screenshot_2024-01-24-00-40-05-37_47b139e01e88b959d11c5a6697f46196.jpg](https://github.com/JGeek00/adguard-home-manager/assets/75412448/a1f1c468-4a5c-45cc-9b3c-22c1bc198799)

For example, when we do client filtering in the filters section, instead of showing the ip addresses here, the names we put on these devices may appear. An extra setting can be added for this

**Comment by JGeek00** [comment]
Added on v2.16.0-beta.1.
