### ISSUE TITLE
Switching to HTTPS does not work

### ISSUE THREAD

**Issue by harsh2029** [JGeek00/adguard-home-manager#119]
It always asks to override SSL verification even if I do it.
![Screenshot_20240128_091810](https://github.com/JGeek00/adguard-home-manager/assets/37512857/47dc28bf-3c65-47b6-8bd2-a34bb5fc8032)
In web browser, https works just fine.

**Comment by JGeek00** [comment]
There you have a handshake exception. The app cannot establish a secure connection with your server. Are you using a self signed certificate?

**Comment by JGeek00** [comment]
If you want I can give you an APK with some debugging traces to check what can be happening.

**Comment by harsh2029** [comment]
Yes, I am using a self-signed certificate signed by my own CA, the CA is however is present in the Android store and I have no problem in browsing through the web browser.
You can provide me the app with debug traces enabled, I can give it a try.

**Comment by JGeek00** [comment]
https://github.com/JGeek00/adguard-home-manager/releases/download/2.15.0-beta.4_(124)/app-release.apk

When you try to connect you will get an unknown error, but I will receive the detailed error on my error tracker.

**Comment by harsh2029** [comment]
My app store just updated the app with your new release 2.15.1 and it is working fine with HTTPS connections 👍 .
I have no issues now even without overriding SSL certificate validation.

I guess you already figured the issue even before I could try your beta version 🤪.

**Comment by JGeek00** [comment]
I really didn't changed anything on the login 🤷🏻
But great that now it works.
