### ISSUE TITLE
Don't show commented lines on Upstream DNS Servers

### ISSUE THREAD

**Issue by Generator** [JGeek00/adguard-home-manager#12]
## Description
Hide commented lines on from Upstream DNS Servers or filter only lines with protocol/ip

![Screenshot_20221021-114856_AdGuard Home Manager](https://user-images.githubusercontent.com/44146/197197271-64c6d6ea-b833-492d-ab8f-9b9b01ca83f2.png)

**Comment by JGeek00** [comment]
Yeah, that has to be changed. I don't want to hide completely comments because if they are there is because the user has added it, but they have to be displayed in a different way. I will work on it. Thanks.

**Comment by JGeek00** [comment]
Fixed on v0.10.2
