### ISSUE TITLE
DNS logs

### ISSUE THREAD

**Issue by winzortdusmani** [JGeek00/adguard-home-manager#120]
Is it feasible for us to access detailed logs specifically for top sources, namely DNS servers? Let's consider a scenario with two DNS servers, assuming one is AdGuard, and the other is Cloudflare. Is it possible to incorporate an option at the bottom of the main screen that allows users to selectively view logs for just the Cloudflare DNS servers? Currently, there is only a copy option available for these at the bottom of the main screen.

**Comment by JGeek00** [comment]
If I understand you correctly, you want a button on the same menu where is the copy button to filter by upstream server on the logs screen?

**Comment by winzortdusmani** [comment]
> If I understand you correctly, you want a button on the same menu where is the copy button to filter by upstream server on the logs screen?

Yes,it will redirect to the logs with that part

**Comment by JGeek00** [comment]
I have to check if the API allows to filter by the upstream DNS

**Comment by JGeek00** [comment]
I think that's not possible. At least, if I input on the logs search field the address of the DNS server, it doesn't return anything.
