### ISSUE TITLE
Featured items ranking

### ISSUE THREAD

**Issue by winzortdusmani** [JGeek00/adguard-home-manager#121]
![Screenshot_2024-01-29-01-46-43-34_47b139e01e88b959d11c5a6697f46196.jpg](https://github.com/JGeek00/adguard-home-manager/assets/75412448/87e94f9d-501e-446d-865c-d9e284cbfe42)

Option can be added to hide any of them from the main menu

**Comment by JGeek00** [comment]
Added on v2.16.0-beta.2.
