### ISSUE TITLE
New update bug

### ISSUE THREAD

**Issue by winzortdusmani** [JGeek00/adguard-home-manager#122]
https://github.com/JGeek00/adguard-home-manager/assets/75412448/10f395ba-5ad0-4958-941b-5eb73a9b7953

This was not the case in the previous version, it shows 0 clients selected. Deselecting the option fixes it. I also noticed that the app wouldn't open after updating the version, deleting and reinstalling solved the problem.
I'm sorry I couldn't check it in the beta versions :)

**Comment by JGeek00** [comment]
The app not starting is a database issue. For me it worked fine, I don't know why each time I update the database there are some users that have problems.

**Comment by JGeek00** [comment]
Fixed on v2.15.1.
