### ISSUE TITLE
Add missing DNS settings

### ISSUE THREAD

**Issue by winzortdusmani** [JGeek00/adguard-home-manager#123]
![Screenshot_2024-01-30-01-24-18-77_e4424258c8b8649f6e67d283a50a2cbc~3.jpg](https://github.com/JGeek00/adguard-home-manager/assets/75412448/c462a83c-1edf-484e-bc49-a14de86ae66c)

**Comment by JGeek00** [comment]
Added on v2.16.0-beta.1.
