### ISSUE TITLE
Adding multi domain for special rules

### ISSUE THREAD

**Issue by winzortdusmani** [JGeek00/adguard-home-manager#124]
![Screenshot_2024-01-30-01-33-43-56_47b139e01e88b959d11c5a6697f46196.jpg](https://github.com/JGeek00/adguard-home-manager/assets/75412448/d4ade567-c087-47a6-a626-67430a63799d)

Here we can provide multiple domain entries instead of a single entry. And also, as in the filters section, a multi-selection mode for deleting domains can be added

**Comment by winzortdusmani** [comment]
And also, as in the filters section, a multi-selection mode for deleting domains can be added

**Comment by JGeek00** [comment]
How is a rule with multiple domains? I thought that wasn't possible

**Comment by winzortdusmani** [comment]
> How is a rule with multiple domains? I thought that wasn't possible

On the web interface, I can add multiple domains at once within a single box, allowing for the consecutive input of domains in a single operation. For instance, if a user has a list related to this (not referring to a whitelist specifically), they can copy and paste 10 domains at once, enhancing ease of use.

**Comment by JGeek00** [comment]
Ah i know what do you mean. I think I will add a raw input box, similar to what the web UI has

**Comment by winzortdusmani** [comment]
> Ah i know what do you mean. I think I will add a raw input box, similar to what the web UI has

Yeah, do you think it would be good?

**Comment by winzortdusmani** [comment]
> Ah i know what do you mean. I think I will add a raw input box, similar to what the web UI has

Yeah, do you think it would be good?

**Comment by winzortdusmani** [comment]
@JGeek00 is it possible to do this for blacklists and whitelists?

**Comment by JGeek00** [comment]
> @JGeek00 is it possible to do this for blacklists and whitelists?

I think that doesn't make much sense because there's no endpoint to add more than one list at the time, and lists require a name apart of the URL.

**Comment by JGeek00** [comment]
Added on v2.16.0-beta.2.
