### ISSUE TITLE
Broken dashboard

### ISSUE THREAD

**Issue by winzortdusmani** [JGeek00/adguard-home-manager#125]
There seem to be changes in the data graphs due to the new adguard home update.

**Comment by JGeek00** [comment]
I have updated to v0.107.44 and I don't see any issues on the graphs

**Comment by winzortdusmani** [comment]
> I have updated to v0.107.44 and I don't see any issues on the graphs

Try holding down

**Comment by JGeek00** [comment]
I don't see any issues with the tooltip. Can you attach a screenshot of the problem?

**Comment by winzortdusmani** [comment]
> I don't see any issues with the tooltip. Can you attach a screenshot of the problem?

https://github.com/JGeek00/adguard-home-manager/assets/75412448/c96a68fe-b7b7-45e3-9fdc-deb47c7d4b8e

This is where I mean, you see the range when I hold it down. Also the graph was not like this before, it was sharper.

**Comment by winzortdusmani** [comment]
Same for PC version

**Comment by winzortdusmani** [comment]
By the way, the result is the same after a clean installation.

**Comment by winzortdusmani** [comment]
By the way, the result is the same after a clean installation.

**Comment by JGeek00** [comment]
I think that depends on the statistics retention time that you have configured

**Comment by winzortdusmani** [comment]
> I think that depends on the statistics retention time that you have configured

Yes, both set for 7 days. But I would like to point out that this happened after the update.

**Comment by JGeek00** [comment]
In that case there's nothing wrong there. You see that "jumps" when you hold the chart because the data points that draw the chart are very separated from each other. There are 7 data points, one for each day.

**Comment by winzortdusmani** [comment]
> In that case there's nothing wrong there. You see that "jumps" when you hold the chart because the data points that draw the chart are very separated from each other. There are 7 data points, one for each day.

![Screenshot_2024-02-07-23-21-26-85_e55d67e6190e80b161828c9e2aa77e01~2.jpg](https://github.com/JGeek00/adguard-home-manager/assets/75412448/87718a17-780b-4c68-bcdc-fce508ee7f9b)

I found an old screenshot, it shows daily, but before it was showing hourly

**Comment by winzortdusmani** [comment]
Ok I think I understand now, is this the change on adguard home?

**Comment by winzortdusmani** [comment]
Ok I think I understand now, is this the change on adguard home?

**Comment by winzortdusmani** [comment]
I thought it was a mistake at first, I just checked the web panel now and realized the difference... For me the old version was better
