### ISSUE TITLE
Optimize scrollbar

### ISSUE THREAD

**Issue by winzortdusmani** [JGeek00/adguard-home-manager#128]
https://github.com/JGeek00/adguard-home-manager/assets/75412448/74e3d1ea-1dc7-461d-a402-568e5b85477e

**Comment by winzortdusmani** [comment]
also applies to the home screen. The bar shortens and lengthens and the screen flickering

**Comment by JGeek00** [comment]
That happens because the top part of the scrolling list gets behind the appbar, that's how the animation works. I think I can make the scrollbar to be always visible but I cannot change that behavior of the video.
