### ISSUE TITLE
Add process time in log

### ISSUE THREAD

**Issue by lutfor-diu** [JGeek00/adguard-home-manager#13]
Brother your app is amazing 😍. Loved it. I have one request if it's possible. Please check the attached image.
![IMG_20221026_205328](https://user-images.githubusercontent.com/32225836/198099153-30a2ec03-daa8-41aa-ad7b-ba8d4c3d7a16.jpg)

**Comment by JGeek00** [comment]
Added on v1.3.0. To enable it go to Settings > General settings > Name and time on logs.
