### ISSUE TITLE
Graph time mismatch

### ISSUE THREAD

**Issue by likkai** [JGeek00/adguard-home-manager#136]
### Steps to reproduce

1. Click the graph and check the number of queries in the graph
2. Graph from web panel is correct, but in this app it's not

### Expected results

Accurate time is shown 

### Actual results

The time is 1 hour behind (9 am appears to be 8 am)

### Screenshots or Video

![Screenshot_20240229-093721_Chrome](https://github.com/JGeek00/adguard-home-manager/assets/76016664/3e11836a-5e5d-4601-b68f-29fcc1b19599)
![Screenshot_20240229-093707_AdGuard Home Manager](https://github.com/JGeek00/adguard-home-manager/assets/76016664/83715331-a01c-4661-b853-caa4e72e3ca6)

### App and OS details

- App version: (eg: v2.16.3)
- Device OS version: (eg: Android 14)

**Comment by JGeek00** [comment]
Fixed on v2.16.4.
