### ISSUE TITLE
Add ... for this client only on logs

### ISSUE THREAD

**Issue by mikropsoft** [JGeek00/adguard-home-manager#139]
### Screenshots

![Ekran Görüntüsü (126)](https://github.com/JGeek00/adguard-home-manager/assets/75412448/e6e0f95a-e145-4a9d-bc5c-63f4449b1080)

![Ekran Görüntüsü (128)](https://github.com/JGeek00/adguard-home-manager/assets/75412448/f3ccae4e-2bb4-45f9-b03e-d9191b70b688)

**Comment by JGeek00** [comment]
Added on v2.17.0-beta.1.
