### ISSUE TITLE
Context menu item in the Query Log to add a Client to the Persistent client list

### ISSUE THREAD

**Issue by mikropsoft** [JGeek00/adguard-home-manager#140]
After the last agh update I couldn't find where the added item in the changes section is. this could be added : https://github.com/AdguardTeam/AdGuardHome/issues/6679

I found a ss from the agh pages for this. I think it's the bottom part. but for some reason this doesn't show up for me : 
![image](https://github.com/JGeek00/adguard-home-manager/assets/75412448/e6c26b6e-37e4-42c2-a698-e43a58151460)

**Comment by JGeek00** [comment]
Added on v2.17.0-beta.1.
