### ISSUE TITLE
Add option to temporarily disable protection

### ISSUE THREAD

**Issue by tomribbens** [JGeek00/adguard-home-manager#142]
### Description

It would be super nice if the app would have the option like on the web admin to disable the protection for a limited time, like the {1, 10, 60} minutes possible on the web admin.

Looking at the [api info](https://github.com/AdguardTeam/AdGuardHome/blob/master/openapi/openapi.yaml) and a quick inspect of the web admin, it seems this should be possible by doing a POST to `/control/protection` with a JSON payload of `{ enabled: false, duration: <microseconds> }`

Additionally, if that functionality could be implemented in a widget that allows quick access to it, and shows the status, that would be even better.

**Comment by JGeek00** [comment]
Hi. I think you are talking about this.
![Screenshot_20240321-220808_AdGuard Home Manager.png](https://github.com/JGeek00/adguard-home-manager/assets/47545344/aebae5db-e55e-4f8c-848c-36c792743b97)

You can see that horizontal list by tapping on the blue box.

**Comment by tomribbens** [comment]
You're right, I did miss that feature in the interface. I'll close this issue now.
