### ISSUE TITLE
老哥，你知道adguardhome模块和Clash模块怎么共存吗？

### ISSUE THREAD

**Issue by setcurl** [JGeek00/adguard-home-manager#144]
### Question

https://github.com/MoGuangYu/Surfing
这是一个Clash模块项目，能研究一下吗？

**Comment by JGeek00** [comment]
AdGuard Home is a DNS proxy, you have to deploy it on your home server. This app is a client to control the AdGuard Home server. AdGuard Home is not something that you install on your smartphone to filter ads.
Here you have more information.
https://github.com/AdguardTeam/AdGuardHome
