### ISSUE TITLE
Client names do not appear in the Filters tab

### ISSUE THREAD

**Issue by mikropsoft** [JGeek00/adguard-home-manager#146]
Hello again, after your account was suspended I thought you would never come back :) 

As in the screenshot, when I go to the clients option in the logs section, I don't see the client names.

![Screenshot_2024-05-30-21-45-41-56_47b139e01e88b959d11c5a6697f46196.jpg](https://github.com/JGeek00/adguard-home-manager/assets/75412448/7b372af4-ed41-4064-a97a-28f4d81ebb11)

**Comment by JGeek00** [comment]
For me they are appearing. I have some devices added to AGH and the name that I gave to each one is appearing on the list just under the IP address.

**Comment by mikropsoft** [comment]
> For me they are appearing. I have some devices added to AGH and the name that I gave to each one is appearing on the list just under the IP address.
> 
> ![Screenshot_20240603-162836_AdGuard Home Manager.png](https://github.com/JGeek00/adguard-home-manager/assets/47545344/58016835-5f69-44ec-97c7-ceb83d054c64)
> 
> 

It must be a bug directly related to my agh system because these are not the ip addresses of my device addresses. I reinstalled umbrel the other day and will try again.

**Comment by mikropsoft** [comment]
OK, there seems to be no problem now, but there is ip spam.
