### ISSUE TITLE
Añadir los clientes al buscador del registro

### ISSUE THREAD

**Issue by juanico10** [JGeek00/adguard-home-manager#147]
Hola,
Añadir los clientes que añades en el apartado:
![Screenshot_20240610-222754.png](https://github.com/JGeek00/adguard-home-manager/assets/95724863/3a7e59d8-d950-4d30-af3b-e412ff079d99)

Estos clientes añadirlos aquí:
![Screenshot_20240610-222416.png](https://github.com/JGeek00/adguard-home-manager/assets/95724863/6051795d-83b5-46c5-82bf-619167c6adf8)

![Screenshot_20240610-222438.png](https://github.com/JGeek00/adguard-home-manager/assets/95724863/94202bbd-2842-4d86-a6fa-408d2d985257)

Añadirlos para que sean más fáciles de buscar en el registro, como botones o filtros. Si quieres mas info escríbeme.

**Comment by JGeek00** [comment]
Esta funcionalidad ya existe. Toca el botón de filtros y después en clientes. Aparece la IP del cliente con su nombre debajo. Tambien se puede usar el buscador de ese panel para buscar por el nombre del cliente.

![Screenshot_20240611-013722_AdGuard Home Manager.png](https://github.com/JGeek00/adguard-home-manager/assets/47545344/2f26abac-9bfb-4af9-8a2d-0f285f04e65b)
