### ISSUE TITLE
[Windows 11][2.17.1] screen_retriever_plugin.dll not found

### ISSUE THREAD

**Issue by Admonstrator** [JGeek00/adguard-home-manager#148]
### Steps to reproduce

1. Installing version 2.17.1 for Windows
2. Trying to start
3. Error: screen_retriever_plugin.dll not found

### Expected results

Program starts

### Actual results

Program fails with _screen_retriever_plugin.dll_ not found message

### Screenshots or Video

Screenshots or video demonstration
![7kuggahosq](https://github.com/JGeek00/adguard-home-manager/assets/69824/7d6ef36f-8924-49e2-aa14-eca64520b38b)

### App and OS details

- Windows 11 23H2
- German language
- AdGuardHomeManager 2.17.1

**Comment by JGeek00** [comment]
Fixed on v2.18.0.

**Comment by Admonstrator** [comment]
Confirmed ✅ 
Thanks for your support!
