### ISSUE TITLE
Hora aplicación

### ISSUE THREAD

**Issue by JuanRodenas** [JGeek00/adguard-home-manager#15]
La hora de la aplicación no se sincroniza con la hora del sistema. Comprobado que en el panel web es correcta.
Adjunto captura:
![Screenshot_20221103-031122.png](https://user-images.githubusercontent.com/95724863/199635709-14cf1f2f-6fc6-4cc1-a529-ff79b1dafff6.png)

Saludos.

**Comment by JGeek00** [comment]
Fixed on v1.5.0
