### ISSUE TITLE
2.19 Doesn't launch

### ISSUE THREAD

**Issue by phoropter** [JGeek00/adguard-home-manager#151]
### Steps to reproduce

Updated to 2.19 today via obtanium and it no longer gets past the initial splash screen.

### Expected results

For the app to work correctly

### Actual results

It only sits at the splash screen

### Screenshots or Video

Screenshots or video demonstration
<img src="https://github.com/user-attachments/assets/8c105f49-4fb5-410d-8d25-21e4d9159539" width="400">

### App and OS details

- App version: v2.19.0
- Device OS version: Android 14 GrapheneOS

**Comment by phoropter** [comment]
I've also uninstalled and reinstalled the app, both using obtanium and manually downloading the apk from github releases.

**Comment by pedrom34** [comment]
Same issue

**Comment by JGeek00** [comment]
Could you try v2.19.0-beta.1? It's weird that's happening because on the emulator and on my Android device it works fine.

**Comment by JGeek00** [comment]
As I see, the problem is only present when you install the app from outside of Google Play. I think the problem is on the updates notifier, because that part of the code is only used when the app is installed from outside of Google Play.

**Comment by phoropter** [comment]
Can confirm this works. Thanks very much for your speedy response!

**Comment by JGeek00** [comment]
If you want to get notified when an update is released I think GitHub has an option to receive an email or a push notification on the GitHub app when a new release is created on the repo. The other option is to get the app from Google Play.

**Comment by phoropter** [comment]
Obtanium automatically polls github for me and pulls updates when available, but thanks for the suggestion.
