### ISSUE TITLE
Client-specific settings

### ISSUE THREAD

**Issue by xynydev** [JGeek00/adguard-home-manager#154]
### Description

Ability to change client-specific settings, configure new clients, and enable/disable blocked services.

### Screenshots

![markup_1000109148](https://github.com/user-attachments/assets/68b9ca5d-924b-4900-a664-7d6c346693d8)
![Screenshot_20241213-223802](https://github.com/user-attachments/assets/39fbff8f-3105-47a1-9b54-bd0f39934522)

### Version where feature was introduced

At least since v1.107.7

**Comment by JGeek00** [comment]
Hi. That feature is already available in the app. Go to Clients > Added and there you will see your added clients.

**Comment by xynydev** [comment]
Thanks! I didn't realize that I have to press and hold the client to see the settings.
