### ISSUE TITLE
Feature Request: Push notification

### ISSUE THREAD

**Issue by fruchttiger87** [JGeek00/adguard-home-manager#17]
Hi, this is not an issue but a feature request: is it possible to add push notification on the smartphone where the app is installed if a configured web address was visited from the home network. In my case it is the video camera that sends data to the manufacturer when the button is pressed. So i could get a push notification when somebody rings the door in an esay way without additional services.

Is that possible?
By the way: fantastic job with the app. It is surprisingly full of features. Thanks for your work.

Best regards
Fruchttiger

**Comment by JGeek00** [comment]
Sorry but that's not possible. The AdGuard Home API does not support that.
