### ISSUE TITLE
Log search more functionality suggestion

### ISSUE THREAD

**Issue by whinnla** [JGeek00/adguard-home-manager#26]
Create the ability to search by client and host at the same

For example if I want to know if a particular ip requested a particular Web address

**Comment by darkj2k** [comment]
Possible to showing client query log by tap client from "Top clients" in Home and "Active Clients" list? The same behavior as "Top queried/blocked domains.

**Comment by JGeek00** [comment]
> Possible to showing client query log by tap client from "Top clients" in Home and "Active Clients" list? The same behavior as "Top queried/blocked domains. 

Please open a new issue for that feature request. To keep a better tracking of it. Thanks.

**Comment by JGeek00** [comment]
Added on v1.11.0.
