### ISSUE TITLE
Encryption details not showing properly

### ISSUE THREAD

**Issue by iAmSaugata** [JGeek00/adguard-home-manager#27]
Encryption details not showing properly on the app. Private key path showing empty, whereas in AdguardHome web, it is showing properly.

![image](https://user-images.githubusercontent.com/26755120/208673633-02b9ff6d-59f1-4607-8b3d-717d7e7f0ce1.png)

![image](https://user-images.githubusercontent.com/26755120/208863119-5af2bce8-44aa-4105-a9ee-67e13ee8f990.png)

Regards,
Saugata D.

**Comment by JGeek00** [comment]
Hi. I'm not using encryption on my AdGuard Home instance. Could you send me what data are you receiving from ``/control/tls/status``?

To get that data do this: go to the encryption screen on the web admin panel, open the developer tools (right click > inspect), go to the network tab and reload the page. There, click on the one described at the beginning (you can check it by placing the mouse over the ``status`` text, go to the response tab and copy it's content. Change all the private data with some placeholder (for example, replace the private key with some text like ``private key text``) and paste it here. 

<img width="1365" alt="image" src="https://user-images.githubusercontent.com/47545344/208785671-f7e103d9-91af-4916-8eb3-0f335fbd38d4.png">

**Comment by iAmSaugata** [comment]
> Hi. I'm not using encryption on my AdGuard Home instance. Could you send me what data are you receiving from `/control/tls/status`?
> 
> To get that data do this: go to the encryption screen on the web admin panel, open the developer tools (right click > inspect), go to the network tab and reload the page. There, click on the one described at the beginning (you can check it by placing the mouse over the `status` text, go to the preview or response tab and copy it's content. Change all the private data with some placeholder (for example, replace the private key with some text like `private key text`) and paste it here.
> 
> <img alt="image" width="1365" src="https://user-images.githubusercontent.com/47545344/208785671-f7e103d9-91af-4916-8eb3-0f335fbd38d4.png">

I have added the screenshot on OP.

**Comment by JGeek00** [comment]
Please try this APK and let me know if it's fixed.

[1.5.7-test.apk.zip](https://github.com/JGeek00/adguard-home-manager/files/10277662/1.5.7-test.apk.zip)

**Comment by iAmSaugata** [comment]
> Please try this APK and let me know if it's fixed.
> 
> [1.5.7-test.apk.zip](https://github.com/JGeek00/adguard-home-manager/files/10277662/1.5.7-test.apk.zip)

Yes, it is working now. I am able to see all the details.

I have one more request, in the DHCP setting, there are three options available.

- Change interface
- Restore leases
- Restore configuration

2nd and 3rd options are not actually Restore, I guess it will be Reset, as I tried it from the application, and it deleted all the static leases from the server, I had to create them again for almost 20+ clients. If you could change the name, it will be more helpful, also if you can add a warning message lie "**This will reset all the existing leases** / **This will reset all the settings**" while clicking it would be one more layer of safety for endusers.

**Comment by JGeek00** [comment]
Ok I will change that and will push an update to Google Play. Thanks.

**Comment by iAmSaugata** [comment]
> Ok I will change that and will push an update to Google Play. Thanks.

Thank you very much. I will continue using it and will update you if I found any bug or suggestions.
