### ISSUE TITLE
[Bug] and [Suggestion] 

### ISSUE THREAD

**Issue by zekabra** [JGeek00/adguard-home-manager#29]
Gracias por las nuevas características de la aplicación, hace unos meses compartí la aplicación en Reddit, cuando me preguntaron si tenía alguna ventaja sobre el uso de la interfaz web de Adguard, la verdad en ese momento era que era sólo una cuestión de preferencia, este ya no es el caso y en mi opinión el éxito de esta aplicación vendrá cuando ofrezca una mejor experiencia que la interfaz de Adguard. Con las nuevas funciones vienen nuevos errores, al hacer clic en uno de los "principales dominios consultados o principales dominios bloqueados" cuando vuelves atrás en lugar de volver a la ventana principal, la aplicación se cierra. Una sugerencia, ahora que en las "reglas personalizadas" ya hay una indicación visual de Permitido o Bloqueado se podrían mostrar los dominios de una forma más limpia, sin ||, ||@@, ^ o $importante, pero para eso era necesario crear la indicación visual "importante" y poner al lado de las ya existentes "Permitido" y "Bloqueado".  La opción copiar dominio al portapapeles también podría estar presente en el registro, esa opción es muy práctica cuando queremos buscar a quien pertenece el dominio en un buscador Otra sugerencia, es mostrar el número total de dominios bloqueados en la ventana principal como lo hace Pihole, Adguard no lo hace y sería más una ventaja para aquellos que utilizan el programa en relación con la interfaz web

Mis mejores deseos para un feliz año nuevo.

**Comment by JGeek00** [comment]
Hola. Ese comportamiento que comentas no es un bug, está diseñado para que funcione así. Cuando se hace click en uno de los dominios, no se abre una nueva pantalla, se redirige de la pestaña de Inicio a la pestaña de Logs, por lo que al no abrirse una nueva ventana, al volver atrás, la app se cierra. 
Con respecto a la lista de reglas personalizadas, mi intención con esa pantalla es mostrar la misma lista que se ve en la interfaz web. Añadí la descripción del tipo de regla para facilitar identificar qué hace cada regla, pero no veo correcto mostrar únicamente si el dominio está bloqueado o no. Quizás eso podría ir en otra nueva pantalla distinta, pero la pantalla de reglas personalizadas tiene que mostrar las reglas completas.
Con respecto a la opción de copiar un dominio desde la pantalla de Logs, ya creaste esta propuesta (https://github.com/JGeek00/adguard-home-manager/issues/23) y será implementada próximamente.

Igualmente, feliz año 2023.
