### ISSUE TITLE
[BUG] Add identifier option is not responding while editing existing client

### ISSUE THREAD

**Issue by iAmSaugata** [JGeek00/adguard-home-manager#30]
Add identifier option is not responding while editing existing client.  This option only working on new entry.

![bug](https://user-images.githubusercontent.com/26755120/210400577-2ffaeacd-c404-49dd-9d1c-551452f066ad.jpg)

I am using latest version from GitHub, do let me know if you need any additional information on this.

Regards,
Saugata D.

**Comment by iAmSaugata** [comment]
Additionally, there is an option to clear cache in web interface, to have this function in the app would be really helpful.

![image](https://user-images.githubusercontent.com/26755120/210402631-768db2b2-2fa1-4ccf-81fc-12ed763cbb48.png)

Regards,
Saugata D.

**Comment by JGeek00** [comment]
Hi. Please open a new issue for the feature request. To have better tracking.

**Comment by JGeek00** [comment]
Fixed on v1.7.0.

**Comment by iAmSaugata** [comment]
Hi,
I have tested this, now I am able to add new identifier.

**Comment by JGeek00** [comment]
Great!
