### ISSUE TITLE
[Feature Request] Add option to clear cache in DNS cache configuration tab

### ISSUE THREAD

**Issue by iAmSaugata** [JGeek00/adguard-home-manager#31]
There is an option to clear cache in web interface, to have this function in the app would be really helpful.
![image](https://user-images.githubusercontent.com/26755120/210626006-4eaa4d1a-e495-4f98-adcc-a02f557a38bf.png)

Regards,
Saugata D.

**Comment by JGeek00** [comment]
Added on v1.8.0.
