### ISSUE TITLE
[Feature Request] Date in log

### ISSUE THREAD

**Issue by zekabra** [JGeek00/adguard-home-manager#33]
In the log it's only possible to see time, if possible add date, similar to what happens in the web interface.
![Screenshot_2023-02-02-01-58-45-017_com jgeek00 adguard_home_manager](https://user-images.githubusercontent.com/24387750/216212946-30b74607-0ace-416b-8574-e3c48b92873b.jpg)

**Comment by JGeek00** [comment]
I think it doesn't make much sense to add the date because you can't get logs older than 2 hours (I think), so all the logs displayed there are from today, or if the new day has just began, from yesterday. I see you are a tablet user, but on mobile phones there's not much space available.

**Comment by zekabra** [comment]
> I think it doesn't make much sense to add the date because you can't get logs older than 2 hours (I think), so all the logs displayed there are from today, or if the new day has just started, from yesterday. I see you are a tablet user, but on mobile phones there's not much space available.

I hadn't remembered that detail. Tks
