### ISSUE TITLE
[Feature Request] Not all "Blocked services" show in app

### ISSUE THREAD

**Issue by xitation** [JGeek00/adguard-home-manager#34]
Hey mate,

App is great, I've however noticed that within the Web console you can block Roblox. However within the android app, under block services Roblox isn't present. Assume others are missing too.

I'm using this to make it easier to allow/disallow access for the kids while on the move. Would be great if the app could have all the services that are available in web console show in the menu.

Thank.

**Comment by JGeek00** [comment]
Added on v1.11.0.

**Comment by xitation** [comment]
Appreciate it, confirmed I can see it fixed in latest version!

Thanks!
