### ISSUE TITLE
Query Log Keyword Search

### ISSUE THREAD

**Issue by stevenflesch** [JGeek00/adguard-home-manager#35]
Love the app, thanks for making it!

Is it possible to add back functionality to the query Log search similar to the last version?  I know now you can search by specific domain name, but you used to be able to filter by keyword.

For example, I used to be able to filter just "api" and I'd see all the domains that had that keyword. Now I can only search by specific domain.

Thanks either way!

**Comment by JGeek00** [comment]
Added on v1.12.0.
