### ISSUE TITLE
Passwordless instance

### ISSUE THREAD

**Issue by Meldrak** [JGeek00/adguard-home-manager#36]
Hi

I would like to test your app, but login/password is mandatory to declare a server

I set up my intances without authentication, so could you add an option to set up server without it?

Regards

**Comment by JGeek00** [comment]
I have to remove that password validation.

**Comment by JGeek00** [comment]
Fixed on v1.12.2.

**Comment by Meldrak** [comment]
Thanks I will try it later, I need to remove the credentials now
