### ISSUE TITLE
Need more languages

### ISSUE THREAD

**Issue by TG-Twilight** [JGeek00/adguard-home-manager#38]
We like your work very much, but it supports too few languages, I hope your work can provide Simplified Chinese,  I hope I can help you in this regard. Thanks you！

**Comment by JGeek00** [comment]
Unfortunately I don't speak Chinese, so I cannot do that.

**Comment by TG-Twilight** [comment]
> Unfortunately I don't speak Chinese, so I cannot do that.

Can I fork your warehouse and submit a Chinese language file to you?  Sir?😀

**Comment by JGeek00** [comment]
Yeah you can do it. If you don't have it install the Flutter framework on your computer and Android Studio to use an Android Virtual Device. Then, I will give you the next steps.

**Comment by TG-Twilight** [comment]
okay, thank you very much！

**Comment by TG-Twilight** [comment]
The installation of Android Studio is complete, and some content of ADGuard Home Manager has been translated.   
![IMG_20230423_144825_683.jpg](https://user-images.githubusercontent.com/121682528/233824476-5ba91129-e4f0-4c39-a841-11b5a088ea65.jpg)

**Comment by JGeek00** [comment]
Great. 
Now open VSCode (or your preferred code editor) and open ``lib/main.dart``.  On line 130 there's the list of supportedLocales. Just add the Chinese language. I think it's  code is``zh-CN``, so you have to add to that list an entry like this: ``Locale('zn', '')``. Don't add the country code, just the language code. Then, inside ``l10n`` directory there are the translation files. Just clone the english one and rename it to ``app_zn.arb`` and replace the english values with the Chinese ones. When you want to test it, first, make sure you have set up an Android Virtual Device on Android Studio. Usually I use Android 13 for development. When you have it, open the project on VSCode and open a terminal, run ``flutter pub get`` to install the required dependencies, and then go to Run > Run without debugging > Dart and Flutter and then select the AVD you created before.

**Comment by TG-Twilight** [comment]
Ok, thanks for the guide, I'll find time to work on this in the next period of time, after which I'll try to pack the files into an apk (hope I can find a way), and finally submit it to you. Thank you for your help.😀

**Comment by JGeek00** [comment]
You don't need to build the APK. When you have it ready just open a Pull Request.

**Comment by JGeek00** [comment]
@zutzo
1. Make sure you have the latest changes available
2. Install the Flutter framework on your computer (if you don't have it)
3. Install Android Studio and create an Android Virtual Device
4. Run ``flutter pub get``
5. Open the Android Virtual Device
6. On Visual Studio Code go to Run > Run without debugging > Dart & Flutter 
7. The app will start on debug mode on the Android Virtual Device

If everything looks fine for you, open a pull request.

**Comment by JGeek00** [comment]
@zutzo  thank you for your work. I added two comments on the PR. When that is solved I will merge it.

**Comment by JGeek00** [comment]
Merged #53

**Comment by JGeek00** [comment]
Added on v2.7.0.
