### ISSUE TITLE
How to set the app?

### ISSUE THREAD

**Issue by SaleemiHaseebullah2001** [JGeek00/adguard-home-manager#40]
Hi, Please can you make a guide on how to set the app?
if there is already a guide showing the procedure to set it up can you share the link?

**Comment by JGeek00** [comment]
Yes, there's a guide about how to set up a connection to your server.

https://github.com/JGeek00/adguard-home-manager/wiki/Create-a-connection

**Comment by SaleemiHaseebullah2001** [comment]
Hi, i am trying to create the connection but it's not working?
i have the ip of the router settings and the username and pass but i don't
have the port number.
and when i try to creat a connection with these above settings and the
https protocol it's saying
SSL error.

help?

**Comment by JGeek00** [comment]
@SaleemiHaseebullah2001  Try using por 443. It's the default port for HTTPS. Also go to Settings > Advanced settings and enable Override SSL validation.
