### ISSUE TITLE
Unable to open settings and advanced options after connecting to adguard server

### ISSUE THREAD

**Issue by server0608** [JGeek00/adguard-home-manager#41]
When I connect to the server, the advanced options and settings are not available. (The display is blank
![Screenshot_2023-04-30-22-16-03-559_com jgeek00 adguard_home_manager](https://user-images.githubusercontent.com/63848847/235357877-f51efa92-df3e-4a4f-a426-367576fa2516.jpg)
![Screenshot_2023-04-30-22-15-54-357_com jgeek00 adguard_home_manager](https://user-images.githubusercontent.com/63848847/235357880-1df7a1e3-8060-41d3-bb10-aed1a4a88484.jpg)

**Comment by JGeek00** [comment]
Hi. Does that happen on other parts of the application or only on that screen?

**Comment by server0608** [comment]
Other parts are normal
![Screenshot_2023-05-01-06-25-26-868_com jgeek00 adguard_home_manager](https://user-images.githubusercontent.com/63848847/235378804-27c17e85-6020-4c93-ba0d-f1eb733289c1.jpg)
And the application version are latest,I also try to reinstall it again and again but useless

**Comment by JGeek00** [comment]
Seeing that I don't really know what could be wrong. I would need you to launch the debug version of the app to see the logs, but for that you will need to install the Flutter framework, Android Studio, Visual Studio code and the project on your computer. If you agree I will give you the instructions to do that. It would be very helpful for me.

**Comment by server0608** [comment]
Sorry, I have never been exposed to any development of android, I tried to install several of the required environments you mentioned, although the environment has been installed, But flutter doctor still showed that the environment was not fully configured, and after more than four hours of trying, I finally decided to abandon the plan.

**Comment by JGeek00** [comment]
Which OS are you using?

**Comment by server0608** [comment]
> What OS are you using?

pc：Windows 10 and ubuntu
phone：MIUI 13

**Comment by JGeek00** [comment]
> > What OS are you using?
> 
> 
> 
> pc：Windows 10 and ubuntu
> 
> phone：MIUI 13 

What's your flutter doctor output? Run flutter doctor -v and paste the results here please.

**Comment by server0608** [comment]
flutter doctor -v
[√] Flutter (Channel stable, 3.7.12, on Microsoft Windows [版本 10.0.17763.4252], locale zh-CN)
    • Flutter version 3.7.12 on channel stable at C:\sdk\fl\flutter_windows_3.7.12-stable\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4d9e56e694 (13 days ago), 2023-04-17 21:47:46 -0400
    • Engine revision 1a65d409c7
    • Dart version 2.19.6
    • DevTools version 2.20.1

This is taking an unexpectedly long time...[X] Windows Version (Unable to confirm if installed Windows version is 10 or greater)

[!] Android toolchain - develop for Android devices (Android SDK version 22.0.1)
    • Android SDK at C:\Users\server0608\AppData\Local\Android\sdk
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components

[!] Android Studio (version 1.2)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    X Unable to find bundled Java version.
    • Try updating or re-installing Android Studio.

[√] VS Code (version 1.77.3)
    • VS Code at C:\Users\server0608\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension can be installed from:
       https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [版本 10.0.17763.4252]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 112.0.5615.138
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 111.0.1661.41

[√] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 4 categories.

**Comment by JGeek00** [comment]
> flutter doctor --android-licenses

That output is normal, don't worry.
Now run this command to accept the licenses: `flutter doctor --android-licenses `

**Comment by JGeek00** [comment]
Also the Android Studio version that you have seems to be very old. Download and install the latest one. https://developer.android.com/studio

**Comment by JGeek00** [comment]
Then you have to create a virtual device on Android Studio. On the home screen click om More actions and on Virtual Device Manager. Click on Create Device and select a Pixel 6 Pro and click Next. On the next screen select Tiramisu (API Level 33) and click Next. Now you can configure the resources for the virtual device. I like to disable the device frame and give it at least 8 GB of internal storage and at least 2 GB of RAM. Then click on finish and start the virtual device clicking on the "Play" button at the right of the row.

**Comment by server0608** [comment]
Things are done,what's the next?

**Comment by JGeek00** [comment]
Download the zip package of the project and uncompress it. Go to [this link](https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter) and install this extension on your Visual Studio Code. Then, open Visual Studio code and open the project's folder. Open a new terminal inside VSCode and run `flutter pub get` to install all the dependencies. When it's done, go to Run > Run without debugging > Dart & Flutter  and select the Android emulator.

**Comment by JGeek00** [comment]
Do this. Reload the app with the green arrow at the top right of VSCode. Then, clear the debug console with the button that has some horizontal lines and a cross. Then, go to settings and send me the whole content of the debug console and a screenshot of the beginning.

**Comment by server0608** [comment]
ebug mode...
main.dart:
I/flutter (19610): FormatException: Invalid radix-10 number (at character 1)
I/flutter (19610): 0-b
I/flutter (19610): ^
I/flutter (19610):
I/flutter (19610): #0      int._handleFormatError (dart:core-patch/integers_patch.dart:126)
I/flutter (19610): #1      int._parseRadix (dart:core-patch/integers_patch.dart:137)
I/flutter (19610): #2      int._parse (dart:core-patch/integers_patch.dart:98)
I/flutter (19610): #3      int.parse (dart:core-patch/integers_patch.dart:60)
I/flutter (19610): #4      compareVersions.<anonymous closure> (package:adguard_home_manager/functions/compare_versions.dart:5)
I/flutter (19610): #5      MappedListIterable.elementAt (dart:_internal/iterable.dart:415)
I/flutter (19610): #6      ListIterator.moveNext (dart:_internal/iterable.dart:344)
I/flutter (19610): #7      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189)
I/flutter (19610): #8      new _GrowableList.of (dart:core-patch/growable_array.dart:150)
I/flutter (19610): #9      new List.of (dart:core-patch/array_patch.dart:52)
I/flutter (19610): #10     SetMixin.toList (dart:collection/set.dart:118)
I/flutter (19610): #11     serverVersionIsAhead (package:adguard_home_manager/functions/compare_versions.dart:90)
I/flutter (19610): #12     Settings.build (package:adguard_home_manager/screens/settings/settings.dart:54)
I/flutter (19610): #13     StatelessElement.build (package:flutter/src/widgets/framework.dart:5038)
I/flutter (19610): #14     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4968)
I/flutter (19610): #15     Element.rebuild (package:flutter/src/widgets/framework.dart:4690)
I/flutter (19610): #16     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950)
I/flutter (19610): #17     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944)
I/flutter (19610): #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953)
I/flutter (19610): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:3682)
I/flutter (19610): #20     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6377)
I/flutter (19610): #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953)
I/flutter (19610): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:3682)
I/flutter (19610): #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993)
I/flutter (19610): #24     Element.rebuild (package:flutter/src/widgets/framework.dart:4690)
I/flutter (19610): #25     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950)
I/flutter (19610): #26     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944)
I/flutter (19610): #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953)
I/flutter (19610): #28     Element.updateChild (package:flutter/src/widgets/framework.dart:3682)
I/flutter (19610): #29     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6377)
I/flutter (19610): #30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953)
I/flutter (19610): #31     Element.updateChild (package:flutter/src/widgets/framework.dart:3682)
I/flutter (19610): #32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993)
I/flutter (19610): #33     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133)
I/flutter (19610): #34     Element.rebuild (package:flutter/src/widgets/framework.dart:4690)
I/flutter (19610): #35     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950)
I/flutter (19610): #36     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5124)
I/flutter (19610): #37     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944)
I/flutter (19610): #38     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953)
I/flutter (19610): #39     Element.updateChild (package:flutter/src/widgets/framework.dart:3682)
I/flutter (19610): #40     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6377)
I/flutter (19610): #41     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953)
I/flutter (19610): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:3682)
I/flutter (19610): #43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993)
I/flutter (19610): #44     Element.rebuild (package:flutter/src/widgets/framework.dart:4690)
I/flutter (19610): #45     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950)
I/flutter (19610): #46     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944)
I/flutter (19610): #47     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953)
I/flutter (19610): #48     Element.updateChild (package:flutter/src/widgets/framework.dart:3682)
I/flutter (19610): #49     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993)
I/flutter (19610): #50     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133)
I/flutter (19610): #51     Element.rebuild (package:flutter/src/widgets/framework.dart:4690)
I/flutter (19610): #52     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950)
I/flutter (19610): #53     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5124)
I/flutter (19610): #54     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944)
I/flutter (19610): #55     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953)
I/flutter (19610): #56     Element.updateChild (package:flutter/src/widgets/framework.dart:3682)
I/flutter (19610): #57     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993)
I/flutter (19610): #58     Element.rebuild (package:flutter/src/widgets/framework.dart:4690)
I/flutter (19610): #59     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950)
I/flutter (19610): #60     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944)
I/flutter (19610): #61     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953)
I/flutter (19610): #62     Element.updateChild (package:flutter/src/widgets/framework.dart:3682)
I/flutter (19610): #63     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6377)
I/flutter (19610): #64     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953)
I/flutter (19610): #65     Element.updateChild (package:flutter/src/widgets/framework.dart:3682)
I/flutter (19610): #66     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993)
I/flutter (19610): #67     Element.rebuild (package:flutter/src/widgets/framework.dart:4690)
I/flutter (19610): #68     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950)
I/flutter (19610): #69     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944)
I/flutter (19610): #70     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953)
I/flutter (19610): #71     Element.updateChild (package:flutter/src/widgets/framework.dart:3682)
I/flutter (19610): #72     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6377)
I/flutter (19610): #73     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953)
I/flutter (19610): #74     Element.updateChild (package:flutter/src/widgets/framework.dart:3682)
I/flutter (19610): #75     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993)
I/flutter (19610): #76     Element.rebuild (package:flutter/src/widgets/framework.dart:4690)
I/flutter (19610): #77     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950)
I/flutter (19610): #78     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944)
I/flutter (19610): #79     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953)
I/flutter (19610): #80     Element.updateChild (package:flutter/src/widgets/framework.dart:3682)
I/flutter (19610): #81     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6377)
I/flutter (19610): #82     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953)
I/flutter (19610): #83     Element.updateChild (package:flutter/src/widgets/framework.dart:3682)
I/flutter (19610): #84     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993)
I/flutter (19610): #85     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5133)
I/flutter (19610): #86     Element.rebuild (package:flutter/src/widgets/framework.dart:4690)
I/flutter (19610): #87     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950)
I/flutter (19610): #88     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5124)
I/flutter (19610): #89     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944)
I/flutter (19610): #90     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953)
I/flutter (19610): #91     Element.updateChild (package:flutter/src/widgets/framework.dart:3682)
I/flutter (19610): #92     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6377)
I/flutter (19610): #93     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953)
I/flutter (19610): #94     Element.updateChild (package:flutter/src/widgets/framework.dart:3682)
I/flutter (19610): #95     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4993)
I/flutter (19610): #96     Element.rebuild (package:flutter/src/widgets/framework.dart:4690)
I/flutter (19610): #97     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4950)
I/flutter (19610): #98     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4944)
I/flutter (19610): #99     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3953)
Exited (1)

**Comment by server0608** [comment]
That's all the information, but “a screenshot of the beginning“.What does that mean?

**Comment by JGeek00** [comment]
Expand the debug console as much as you can and scroll the debug console back to the top and take a screenshot of that.

**Comment by JGeek00** [comment]
I think I know what's happening. 

Do this please:
1. Open the web admin panel on your computer
2. Open the developer tools (Chrome is right click > inspect)
3. Go to network tab
4. Refresh the page 
5. Enter on the result that says "Status"
<img width="1365" alt="image" src="https://user-images.githubusercontent.com/47545344/235697785-bd8d0906-b78b-48ac-a4ad-669316a29b77.png">
6. Send me a screenshot of this screen (hide the DNS addresses)
<img width="1308" alt="image" src="https://user-images.githubusercontent.com/47545344/235698570-68d2a4e4-c58b-4c44-a053-8002ab6f8878.png">
7. Go to the entry that says "version.json" and send me a screenshot of it
<img width="1308" alt="image" src="https://user-images.githubusercontent.com/47545344/235698899-6ba58f46-7e68-4011-9f9e-49ebb402a9cc.png">

**Comment by server0608** [comment]
I'm very sorry that I couldn't reply to your message in time because I went to school. The following is a screenshot according to your request. My address is not hidden because it is a private address.
![image](https://user-images.githubusercontent.com/63848847/236618589-3b11abac-4040-4fd9-ae7b-116b15e3408c.png)
![image](https://user-images.githubusercontent.com/63848847/236618626-3df2fc3e-ee43-48e5-aadb-afd08b52b52b.png)

**Comment by JGeek00** [comment]
It should be fixed on v2.1.1.
