### ISSUE TITLE
Show friendly/added names in app

### ISSUE THREAD

**Issue by tejasraman** [JGeek00/adguard-home-manager#42]
I really love your app, but I have one slight problem with this app: it does not show "friendly names" in the query logs. The names, however, show up in the web interface.

![Screenshot_20230430-213951.png](https://user-images.githubusercontent.com/96961804/235403245-82ed6900-4ee4-4873-9126-4ea853a52be9.png)

![Screenshot_20230430-213917.png](https://user-images.githubusercontent.com/96961804/235403248-e34f04a9-b3ba-4cca-92be-6de64a16150d.png)

![Screenshot_20230430-214939.png](https://user-images.githubusercontent.com/96961804/235403905-ca2b90be-eba9-4018-8c77-58042ebd0611.png)

Is there any possibility that the ability to show friendly names can be added to the app?

**Comment by JGeek00** [comment]
Hi. Go to Settings > General Settings and enable Show name and time on logs.

**Comment by tejasraman** [comment]
Thanks so much @JGeek00 that worked
