### ISSUE TITLE
Add Date or Time beside DNS Queries in the graph

### ISSUE THREAD

**Issue by sannidhyaroy** [JGeek00/adguard-home-manager#45]
The Home tab displays the graph of DNS Queries vs time. In the web ui, I can hover over the graph and it shows me the value of number of DNS Queries vs the time or date. In your app, if I touch and hold on a certain point in the graph, it only shows the value of DNS Queries (value of the ordinate) at that point. It'd be helpful if you also include the date or time (value of the abscissa).

Also a minor bug that I noticed is in the Settings tab, if I tap on "Access Settings", it opens up the "Allowed Clients" tab and since the list is empty in case of mine, it says, "No hay clientes permitidos". My language is set to English, so in the "Blocked Clients" tab, it says, "No blocked clients". Only the "Access Clients" message is displayed in Spanish.

**Comment by JGeek00** [comment]
Hi that issue will be fixed on the next release. Probably tonight or tomorrow. I opened another issue just for it (#46).

The problem with the timestamp on the chart is that I don't receive that information from the API, I only receive a list of numbers, which are the values. But maybe I can calculate it looking at the statistics retention time configuration.

**Comment by sannidhyaroy** [comment]
> But maybe I can calculate it looking at the statistics retention time configuration.

So, it's the issue with the API then? I guess then I could open an issue in the official repo of AdGuard Home as a feature request.

Alternatively, you probably could use a bit of Web Scraping, I guess. Thought that probably make this complicated. I'm a noob in Flutter so I don't know if my suggestions are feasible.

**Comment by JGeek00** [comment]
It would be great if the AdGuard Home people add the timestamps on the response of the API.

**Comment by JGeek00** [comment]
Added on v2.5.0-beta.2
