### ISSUE TITLE
Home tab UI issues in v2.3.1

### ISSUE THREAD

**Issue by sannidhyaroy** [JGeek00/adguard-home-manager#47]
The changelog for v2.3.1 seems to state that it fixes UI issue on homescreen. However, in my case, in the home and settings tab, the title of the AppBar widget seems to be displaced a bit down. When I scroll, it then goes back to its original position.

Is this intentional or a bug?
![Screenshot_20230521-131913_Pixel Launcher.png](https://github.com/JGeek00/adguard-home-manager/assets/58990408/efd398f3-95c0-4c39-81bd-037995860a02)

**Comment by JGeek00** [comment]
That's intentional. It's de new appbar design of Android 12. I will continue implementing it on the rest of the application.
