### ISSUE TITLE
Log filters

### ISSUE THREAD

**Issue by HyperCriSiS** [JGeek00/adguard-home-manager#49]
Hi :)
Can you please add the log enhancements like you did for the Droidhole app?
Like filters and search functions.
Also it would be nice to configure the used search engine.

Thanks and regards
Hyper

**Comment by JGeek00** [comment]
The system that AdGuard Home has is much simpler. It only allows one search term at a time. So you can't filter by two domains or one domain and one device...

**Comment by HyperCriSiS** [comment]
OK, but would ne nice of you can add two buttons above the search at right and left for fast switch between blocked and allowed :)
Also really missing the research button for fast Internet search. Startpage as engine would be great 😅

**Comment by JGeek00** [comment]
Yeah, I can add a toggle to switch quickly between allowed, blocked and all, and also the internet search button.

**Comment by JGeek00** [comment]
Added on v2.6.0-beta.1
