### ISSUE TITLE
Home screen

### ISSUE THREAD

**Issue by HyperCriSiS** [JGeek00/adguard-home-manager#50]
Hi,

I really liked the home screen of the Droidhole app, especially this:
![Screenshot_20230710-014056_Firefox_Nightly_1](https://github.com/JGeek00/adguard-home-manager/assets/11708192/57c9d7be-6455-4894-b628-dcd2bba11db2)

The server status is rather boring 😅
I would prefer it not to take this much space.
What do you think?

Thanks and regards
Hyper

**Comment by JGeek00** [comment]
The app has something similar to that. It's called the "combined chart". Enable it at Settings > General settings.

**Comment by HyperCriSiS** [comment]
OK thank you, that's a bit better. Can you add Domains on Adlist?

**Comment by HyperCriSiS** [comment]
Can you maybe add the possibility to hide parts of the home screen?
Blocked malware/phising and
Blocked adult websites

Will never show anything as I have not enabled them.

**Comment by HyperCriSiS** [comment]
Oh 🤦‍♂️ thanks, sorry did not see 😅
