### ISSUE TITLE
Add Polish translation

### ISSUE THREAD

**Issue by Akszyn** [JGeek00/adguard-home-manager#57]
No Polish but I will be happy to help translate

**Comment by JGeek00** [comment]
Hi. This are the steps that you hace to follow:

1. Install the [Flutter framework](https://docs.flutter.dev/get-started/install) on your machine
2. Install a code editor if you don't have it. I recommend [Visual Studio Code](https://code.visualstudio.com/)
3. Clone this repository on your machine
4. Open the project folder into VSCode
5. Run ``flutter pub get`` to install the dependencies
6. Inside ``lib/l10n``, clone ``app_en.arb`` and rename it to ``app_pl.arb``
7. Open ``lib/main.dart``, go to the ``supportedLocales`` array (line 227) and add the new entry. It would look like this:
  ```
        supportedLocales: const [
          Locale('en', ''),
          Locale('es', ''),
          Locale('zh', ''),
          Locale('zh', 'CN'),
          Locale('pl', ''),
        ],
  ```
8. Go back to ``app_pl.arb`` and replace all the English values with the Polish translation
9. To test the changes you can use your own physical device. To do that you have to enable USB debugging on the device, and then connect it to the computer. The device name should appear on the bottom right corner of the VSCode window.
10. To run the app on your physical device you have to uninstall first the version that you downloaded from Google Play, and then on VSCode go to Run > Run without debugging > Dart & Flutter. If it asks you about what device do you want to use, select your physical device
11. The alternative if you don't want to use your physical device is to run it on a virtual device. To do that you have to install Android Studio on your computer, and then create a virtual device on Android Studio. Then, go back to VSCode, and on the bottom right corner of the window, where the selected device appears, click on it and select the virtual device that you have just created. Then click on Run > Run without debugging and the app should start on the virtual device.

**Comment by JGeek00** [comment]
@Akszyn one small change. Instead of cloning the repository, fork it, and when you have it ready, open a pull request.

**Comment by Akszyn** [comment]
@JGeek00 Is it easier you could create a file for the Polish language? and I would just download one file and translate it

**Comment by JGeek00** [comment]
> @JGeek00 Is it easier you could create a file for the Polish language? and I would just download one file and translate it than to download the entire repository 

If that's easier for you I will do it on that way.

**Comment by JGeek00** [comment]
Hi @Akszyn just copy [this file](https://github.com/JGeek00/adguard-home-manager/blob/master/lib/l10n/app_en.arb) and translate the values.

**Comment by Akszyn** [comment]
@JGeek00 Everything as it flies I can explain there or any values do not just move and after translating I have to replace the contents of this file?

**Comment by JGeek00** [comment]
@Akszyn you have to copy the content of that file on a new file and replace the values of the right with it's translation.

**Comment by Akszyn** [comment]
Please make this translation available as a beta version of the application because you can always correct something easier

> @Akszyn one small change. Instead of cloning the repository, fork it, and when you have it ready, open a pull request.

gives a request to download to the beta version because I do not know if it is translated correctly semantically because I do not even have how to check because I could not configure the server Adguard Home

**Comment by JGeek00** [comment]
@Akszyn if you need help to configure an AdGuard Home server just tell me, I can help you. And yes, I will release a beta version with the translation, maybe with some other changes.

**Comment by Akszyn** [comment]
@JGeek00 If you would like to help me with the configuration of this server, write to me on fb.com/akszyn in order not to clutter this thread with off-topic messages

**Comment by JGeek00** [comment]
@Akszyn for me it's not a problem to give you the instructions on this thread. I don't have Facebook.

**Comment by JGeek00** [comment]
Added on v2.8.0.
