### ISSUE TITLE
Charts visual bug

### ISSUE THREAD

**Issue by marek-guran** [JGeek00/adguard-home-manager#58]
When you want to see first or last values on charts, it's hidden. This could be easily resolved if the window for displaying these values was moved to left or right if it will overflow the chart. (See below images)
![Screenshot_20230831-080651_AdGuard Home Manager.png](https://github.com/JGeek00/adguard-home-manager/assets/26904790/fc67b943-44f1-4de2-be91-aa661ef1eb37)

![Screenshot_20230831-080719_AdGuard Home Manager.png](https://github.com/JGeek00/adguard-home-manager/assets/26904790/0345bc58-dcbd-4b50-9415-ee958ee6c41e)

**Comment by JGeek00** [comment]
I can't do much about that because that tooltip is generated and controlled by the charts library. Will check if the library has an option to prevent that from happening.

**Comment by JGeek00** [comment]
The charts library has a parameter to prevent that from happening. It will be fixed on the next release of the application,
