### ISSUE TITLE
Feature statistics viewer locking and queries

### ISSUE THREAD

**Issue by JuanRodenas** [JGeek00/adguard-home-manager#60]
Hello!

I request that you put in settings an option to be able to see the general statistics of blocking and queries as in the first versions of the app.
A screenshot of how I request it.
![imagen](https://github.com/JGeek00/adguard-home-manager/assets/95724863/97aca199-5d5e-4021-916b-b489671be227)

You can set an option to view it as in the current version and as in the first versions of the app. You can set the setting in (Settings > General settings).

Best regards,
Juan

**Comment by JGeek00** [comment]
https://github.com/JGeek00/adguard-home-manager/issues/64
