### ISSUE TITLE
Turkish Language Support Request

### ISSUE THREAD

**Issue by mrydev** [JGeek00/adguard-home-manager#63]
Hello, we have translated the strings in the application into Turkish language, but we cannot send them with pull request. We have an .arb file. How can we deliver it to you?
[app_tr.arb.txt](https://github.com/JGeek00/adguard-home-manager/files/13043731/app_tr.arb.txt)

**Comment by mrydev** [comment]
There are no errors in the translation, by the way. I checked it.

**Comment by mdksec** [comment]
[app_tr.arb.txt](https://github.com/JGeek00/adguard-home-manager/files/13044062/app_tr.arb.txt)

we have updated the translation. use this. where should we send this file for the next update?

**Comment by JGeek00** [comment]
Hi @mdksec @mrydev 
Just upload the file here. And for future updates you can open a new issue indicating that you have updated the translation file and just add the file to the comment.

**Comment by mdksec** [comment]
thanks, i made a few changes. i would appreciate if you include this in the next update
[app_tr.arb.txt](https://github.com/JGeek00/adguard-home-manager/files/13063182/app_tr.arb.txt)

**Comment by JGeek00** [comment]
Translation added on v2.9.0. That release includes some new texts that need to be translated, so check the latest version of the translations file to add that new strings.

**Comment by mrydev** [comment]
Ok, we will translate the new strings and send them.

**Comment by mdksec** [comment]
[app_tr.arb.txt](https://github.com/JGeek00/adguard-home-manager/files/13071927/app_tr.arb.txt)
![markup_1000001551](https://github.com/JGeek00/adguard-home-manager/assets/75412448/746318f7-51fa-4036-b6b7-c3581ed31ffd)
![markup_1000001552](https://github.com/JGeek00/adguard-home-manager/assets/75412448/e8afa24c-e459-4dd7-90d1-0542d9fd9dba)

Updated. However, the strings I show in the photo are not in the translation. Is this normal?

**Comment by mdksec** [comment]
thanks. can i write to you via telegram to send the next updated translations or any problem reports. also if you have a group i would like to join
