### ISSUE TITLE
Interface issues

### ISSUE THREAD

**Issue by mdksec** [JGeek00/adguard-home-manager#65]
OK. We can explain interface issues under this topic.

![Ekran Görüntüsü (37)](https://github.com/JGeek00/adguard-home-manager/assets/75412448/09584377-4b28-4e6c-930e-1a3c4a328c77)

First of all. what I've seen is only for the pc version. 
there is a color difference in the part I marked at the top. this is not a problem, but I think it would look better if it was the same color. secondly, at the bottom, the show more section collides with the numbers. even though I scroll all the way down.

![Ekran Görüntüsü (38)](https://github.com/JGeek00/adguard-home-manager/assets/75412448/33e666e5-c11c-4b64-a952-7676741e0a76)

Here. I can't move the part I marked.

![Ekran Görüntüsü (39)](https://github.com/JGeek00/adguard-home-manager/assets/75412448/62a547ec-eb14-43e6-9cec-03d904f352cd)

where I marked, whatever it's called, the button looks half.
That's all that caught my eye so far.

**Comment by JGeek00** [comment]
Color issue: for now I won't change anything because I'm thinking about replacing the navigation rail with a drawer.
Arrow button: i think I have fixed it.
Time chips: you can scroll it by swiping horizontally using the touchpad, but I will add a visible scrollbar for desktop
Settings list: fixed
