### ISSUE TITLE
[BUG] App doesn't allow sub.subdomain.domain.tld

### ISSUE THREAD

**Issue by Generator** [JGeek00/adguard-home-manager#7]
Trying to setup my host using duckdns.org, AdGuard Home has his own domain (dns.subdomain.duckdns.org), but the app only accepts subdomain.duckdns.org.

**Comment by JGeek00** [comment]
Hello! Thanks for reporting the issue. It will be fixed on next release.

**Comment by JGeek00** [comment]
Fixed on v0.8.0.
