### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by mdksec** [JGeek00/adguard-home-manager#73]
In the logs section, "select time range" option can be added to the filtering section. this can be added to other parts

**Comment by mdksec** [comment]
there is also probably no "average processing time" text in the home page section of the web panel. it would be good if this is added.

**Comment by mdksec** [comment]
Major metasources and, Average metasource response time . an extra table of these could be added, it is missing :)

**Comment by JGeek00** [comment]
> In the logs section, "select time range" option can be added to the filtering section. this can be added to other parts

I wanted to add that filter, but the AdGuard Home API doesn't have that option.

**Comment by JGeek00** [comment]
Also that other options I think that they have been added recently to AdGuard Home right?

**Comment by JGeek00** [comment]
I created a new issue to add that lists
https://github.com/JGeek00/adguard-home-manager/issues/74
