### ISSUE TITLE
Update failed

### ISSUE THREAD

**Issue by mdksec** [JGeek00/adguard-home-manager#77]
I think the last update was 1 week ago, I don't remember exactly. When I pressed the update button from the app, it gave an error, I don't know the exact error code, but it's not important. Then I refreshed the page and saw that the server was updated. What do you know about this?

**Comment by JGeek00** [comment]
Probably that was because the update took a bit longer than usual and one of the requests to check if the server has been updated failed. No worries if it finally updated successfully.
