### ISSUE TITLE
Select from list feature

### ISSUE THREAD

**Issue by mdksec** [JGeek00/adguard-home-manager#78]
I think that the "select from list" option in the disability list section in the web panel should be added to the application

**Comment by JGeek00** [comment]
What option is that one?

**Comment by mdksec** [comment]
> What option is that one?

It's in the blacklist adding section. Apart from adding a custom domain, we can select designated lists from there.

**Comment by JGeek00** [comment]
I have been checking it and it seems that the data doesn't come from the API, so I cannot add it to the app.
