### ISSUE TITLE
App scale feature

### ISSUE THREAD

**Issue by mdksec** [JGeek00/adguard-home-manager#79]
On linux, it would be nice if there was a scale adjustment (or in general). on ubuntu I use the large font feature (it looks like the scale is 125%) but the program can't adapt to it.

![Ekran Görüntüsü - 2023-11-25 16-57-15](https://github.com/JGeek00/adguard-home-manager/assets/75412448/9b029ea2-0193-4376-9ba1-1cb4cbd55196)

**Comment by JGeek00** [comment]
I have tested it and I don't have any issues with Ubuntu 22.04.

![100](https://github.com/JGeek00/adguard-home-manager/assets/47545344/43467d91-cb80-4f6d-bab0-490ac6148d36)
![150](https://github.com/JGeek00/adguard-home-manager/assets/47545344/8d64f0bf-c060-44da-ad5a-b97c751861e1)
![200](https://github.com/JGeek00/adguard-home-manager/assets/47545344/deb578a6-007c-4afd-a74f-44a189741bf0)

**Comment by mdksec** [comment]
> I have tested it and I don't have any issues with Ubuntu 22.04.
> 
> ![100](https://github.com/JGeek00/adguard-home-manager/assets/47545344/43467d91-cb80-4f6d-bab0-490ac6148d36)
> ![150](https://github.com/JGeek00/adguard-home-manager/assets/47545344/8d64f0bf-c060-44da-ad5a-b97c751861e1)
> ![200](https://github.com/JGeek00/adguard-home-manager/assets/47545344/deb578a6-007c-4afd-a74f-44a189741bf0)
> 

No, it already gets bigger when you change the scale in the settings, this is not a problem, I keep it at 100% scale but the large font feature is on. Take a look at the accessibility settings. When you turn it on, it looks like 125%, but normally the scale is 100%, so it looks like what I posted in the photo. it doesn't matter man, you can add it as an extra feature. It's up to you

**Comment by JGeek00** [comment]
Ah, now I know what you mean. Previously I had setup a fixed text size to prevent big text from being overflowed or breaking the layout, but I have removed it. That change will be applied on the next release.
