### ISSUE TITLE
Cannot change screen after entering on list reorder

### ISSUE THREAD

**Issue by mdksec** [JGeek00/adguard-home-manager#81]
[Ekran Kaydı - 30-11-2023 19:25:32.webm](https://github.com/JGeek00/adguard-home-manager/assets/75412448/388d0176-5f0f-4b4a-b2a7-3d93cce92c05)

Sorting not working (press and hold disabled)
and when that menu opens, you can't change between menus like in the video

**Comment by JGeek00** [comment]
Fixed on v2.12.3.
