### ISSUE TITLE
Adguard home update

### ISSUE THREAD

**Issue by stablelover0** [JGeek00/adguard-home-manager#82]
In the DNS server configuration settings, 3 new settings have been added after the new update. (Or I may have just noticed it) but add it to the app bro . (Speed limiting permission list. Also a setting for ipv4 and ipv6)  I would also like you to add one more thing, in the DHCP settings it should give an error if DHCP is not available. I don't have dhcp and when I open that setting I get the warning "Loading DHCP settings".

**Comment by mdksec** [comment]
and the ability to specify a client-specific dns server seems to have arrived

**Comment by mdksec** [comment]
Ability to set client's custom DNS cache added

**Comment by JGeek00** [comment]
Yeah, there are still a few features that were added on the latest versions of AdGuard Home that are missing on the app.

**Comment by JGeek00** [comment]
> And the "access list" at the bottom of the DNS settings, Why isn't this added? And backup dns servers idk, there are a few things missing, but it's not very important. And the button to test the top server, I don't know if this is there, but I didn't see it. if there is something more missing, I'll tell you.

The "access list" on the app is outside the DNS settings. It's located at "Access settings" on the main settings page.

**Comment by JGeek00** [comment]
Please create an specific issue for each feature request including an screenshot of where it is located on the web app and the version of AdGuard Home since it's available.

**Comment by stablelover0** [comment]
> Please create an specific issue for each feature request including an screenshot of where it is located on the web app and the version of AdGuard Home since it's available.

Oh thx, I know you are aware of these, I just wanted to remind you so that the app is updated :)

**Comment by JGeek00** [comment]
I have created an individual issue to handle each new feature, so I'm closing this issue.
