### ISSUE TITLE
DHCP settings infinite load when server doesn't support DHCP

### ISSUE THREAD

**Issue by winzortdusmani** [JGeek00/adguard-home-manager#86]
the last update doesn't seem to have worked for me, it still shows the loading screen.

**Comment by JGeek00** [comment]
How do you have your AdGuard Home server set up? OS? Docker?

**Comment by stablelover0** [comment]
> How do you have your AdGuard Home server set up? OS? Docker?

windows 10.

**Comment by JGeek00** [comment]
Fixed on v2.15.0-beta.4.
