### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by stablelover0** [JGeek00/adguard-home-manager#88]
![Ekran Görüntüsü (31)](https://github.com/JGeek00/adguard-home-manager/assets/75412448/edeb6892-417e-40ec-8494-3893f90fd2ad)

in the places I marked in the picture, separation into tables can be added to make it look nicer, like where I marked the number of requests. also a refresh button for each section. and it looks like 2 buttons have been added above the value that says 6.315. when clicked, it seems to sort from small to large. this applies to all 4 tables.

![Ekran Görüntüsü (33)](https://github.com/JGeek00/adguard-home-manager/assets/75412448/7afadbbe-7d9f-4940-9163-1f5075f46211)

the text "featured top sources" looks a bit awkwardly placed. the ring diagram to the left of it could be removed, or it could be added to the same section as "top source average response time" to make it look nicer. these are my ideas. good luck.

**Comment by stablelover0** [comment]
and I noticed that I can't refresh this page on the pc, f5 doesn't seem to work. scrolling down like on the phone is of course not available.

**Comment by JGeek00** [comment]
About the ring chart, I'm thinking about replacing it with a segmented bar, it wouldn't take as much space and it would be equally meaningful.

**Comment by JGeek00** [comment]
I won't add that refresh button for each section because it doesn't make any sense because all the data for each section comes from the same endpoint, so it makes more sense to have a global refresh button.

**Comment by JGeek00** [comment]
It would be a good idea to have an option to sort the list items on the reverse way, but I will add it on the dedicated screen with all the results, because that section on the home screen is more like a summary.

**Comment by JGeek00** [comment]
I have created issues #94 #95 and #96 to handle that suggestions
