### ISSUE TITLE
A small change on the home page

### ISSUE THREAD

**Issue by stablelover0** [JGeek00/adguard-home-manager#89]
![Ekran Görüntüsü (34)](https://github.com/JGeek00/adguard-home-manager/assets/75412448/2d1bd523-8a52-4e31-a908-2b81f390a6f7)

for example, it would be nicer if the graph in the "blocked adult content" section still shows the graph, instead of being blank when the value is 0.

![Ekran Görüntüsü (35)](https://github.com/JGeek00/adguard-home-manager/assets/75412448/d7241d89-5309-4197-96af-8e47733740d2)

Also optionally, when we mouse over the ring diagram on the left side or press and hold on it while on the phone, the number can appear, as in the figure at the top of the home page.

**Comment by JGeek00** [comment]
About the first one, I cannot draw a chart if it has no data. But I agree that on desktop mode it looks strange, so I think it would be a good idea to put there a placeholder.
About the second one, I understand that you want a tooltip. I need to take a look at the library that I'm using to draw that chart to check if it has that option.

**Comment by JGeek00** [comment]
Created #108 and #109
