### ISSUE TITLE
Configuration with HA

### ISSUE THREAD

**Issue by joaopedros2** [JGeek00/adguard-home-manager#9]
I can't configure access to my Adguard home addon installed on home assistant

**Comment by JGeek00** [comment]
Hi. Could you give me more details about how do you establish a connection with an AdGuard Home server running on Home Assistant. Mine is running on a Docker container on my NAS. I don't know if something is different.

**Comment by joaopedros2** [comment]
I use this URL: https://192.168.1.***:8123/a0d7b954_adguard

IP from my home assistant and port. Another

**Comment by joaopedros2** [comment]
![Screenshot_2022-10-14-11-54-09-72_47b139e01e88b959d11c5a6697f46196](https://user-images.githubusercontent.com/50808090/195830487-9a33e46d-946c-483b-a92f-acdb809cfe45.jpg)

**Comment by joaopedros2** [comment]
the path should be before the port

**Comment by JGeek00** [comment]
You have to use the same URL as the AdGuard Home web admin panel, with the same credentials.

Open the AdGuard Home web admin panel from HomeAssistant, and then insert the data inside the app. IP address on IP field, all the following stuff until the port on path field, and the port on port field.

**Comment by joaopedros2** [comment]
> You have to use the same URL as the AdGuard Home web admin panel, with the same credentials.
> 
> Open the AdGuard Home web admin panel from HomeAssistant, and then insert the data inside the app. IP address on IP field, all the following stuff until the port on path field, and the port on port field.

I can't find that panel.

![Screenshot_2022-10-15-10-01-39-11_47b139e01e88b959d11c5a6697f46196](https://user-images.githubusercontent.com/50808090/195978452-15782460-caa6-4c3c-a044-6ee73e08d17c.jpg)

I try use de IP only and a get SSL error

**Comment by joaopedros2** [comment]
I have to activate de port 80 for the web interface but I have the same error with SSL.

**Comment by JGeek00** [comment]
For the SSL error you have to go to Settings > Advanced setting and enable Override SSL check.

**Comment by joaopedros2** [comment]
I get a error 
![Screenshot_2022-10-15-19-20-52-29_47b139e01e88b959d11c5a6697f46196](https://user-images.githubusercontent.com/50808090/196006661-492f24c2-e6e6-41bf-a11b-dad53a17d78e.jpg)

**Comment by JGeek00** [comment]
Please, send me the app logs, so I can know what is causing that error. 
Go to Settings > Advanced settings > Logs, and tap on the share icon. That will copy the logs to the clipboard, and then, paste them here.

**Comment by joaopedros2** [comment]
error code not expected

**Comment by JGeek00** [comment]
I need also the statusCode and the resBody.

**Comment by joaopedros2** [comment]
![IMG_20221016_212644](https://user-images.githubusercontent.com/50808090/196056603-d57ddb25-a47d-4c7b-b054-cfbc5a1dadb8.jpg)
![IMG_20221016_212603](https://user-images.githubusercontent.com/50808090/196056605-eaf9c70e-59fe-47d6-8f15-4e6849fd2815.jpg)
![IMG_20221016_212532](https://user-images.githubusercontent.com/50808090/196056607-f794905c-f7fd-4465-ac3d-f5f176e55363.jpg)

**Comment by JGeek00** [comment]
I think I have figured out how to connect to an AdGuard Home server running on Home Assistant. You will need to set a port for the web interface on the settings.

<img width="1035" alt="image" src="https://user-images.githubusercontent.com/47545344/196060403-1d52cbe5-9bf5-40cc-b73a-285b31c7b244.png">

I will release an update soon adding support for this special case. There will be a toggle on the add server screen, and if your AdGuard Home server is running on Home Assistant, you will have to enable it.

**Comment by joaopedros2** [comment]
I already have the port 80 set for the web interface.
I will wait for the update, thanks 🙏

**Comment by JGeek00** [comment]
I have just released v0.9.1 fixing this issue. Let me know if now it works for you.

**Comment by JGeek00** [comment]
Ok. Pefect!
For the new problems, please open a new issue for each one. I will close this issue.
