### ISSUE TITLE
Add extra setting in dns section

### ISSUE THREAD

**Issue by stablelover0** [JGeek00/adguard-home-manager#90]
![Ekran Görüntüsü (36)](https://github.com/JGeek00/adguard-home-manager/assets/75412448/234dd2df-500b-42f0-9c28-bbdd8c7dcd68)

backup dns servers.

![Ekran Görüntüsü (37)](https://github.com/JGeek00/adguard-home-manager/assets/75412448/906794a8-3a18-4131-8962-185408e459ab)

button to test dns server. result when servers are working properly: "The specified DNS servers are working properly"

![Ekran Görüntüsü (38)](https://github.com/JGeek00/adguard-home-manager/assets/75412448/d04e4195-1837-493f-9175-da878cb09765)

and also the option "use private ip for edns" seems to be missing

**Comment by JGeek00** [comment]
I have created issues #92 and #93 to handle that feature requests. For the next time, please, create one issue for each request, and give it a more descriptive title.
