### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by stablelover0** [JGeek00/adguard-home-manager#91]
![Ekran Görüntüsü (51)](https://github.com/JGeek00/adguard-home-manager/assets/75412448/7d8c7d2f-4677-47ae-972d-d14c2d29167a)

When a dns rewrite is added or deleted on the pc, 2 warning messages appear.

**Comment by stablelover0** [comment]
And I noticed another little problem.

https://github.com/JGeek00/adguard-home-manager/assets/75412448/a087e11f-71de-408d-844b-b859a0a4bc1d

I think it should show a warning sign by default.

**Comment by JGeek00** [comment]
I know about the issue of the two snackbars. I think it's not important and that's why I haven't taken a look at it yet, but I will try to fix it.

**Comment by JGeek00** [comment]
About the ! icon on the encryption settings, it appears when there are some fields with invalid values, or the form hasn't been edited.

**Comment by JGeek00** [comment]
I created #97 to handle the snackbars issue
