### ISSUE TITLE
Duplicated snackbars desktop mode DNS rewrites

### ISSUE THREAD

**Issue by JGeek00** [JGeek00/adguard-home-manager#97]
![image](https://github.com/JGeek00/adguard-home-manager/assets/47545344/93df631b-ba89-4867-bab9-7aab64c5a473)

**Comment by winzortdusmani** [comment]
By the way, this bug is not only in this section, it is the same in other sections

**Comment by JGeek00** [comment]
It should be fixed on the latest version (v2.15.0)

**Comment by winzortdusmani** [comment]
> It should be fixed on the latest version (v2.15.0)

Okay, I'll try again and report back
