### ISSUE TITLE
Add a redirect option on the home screen

### ISSUE THREAD

**Issue by thestablelover** [JGeek00/adguard-home-manager#98]
https://github.com/JGeek00/adguard-home-manager/assets/75412448/892fb0cc-5ae9-41ff-a146-c1b05871b9d7

Frames can be added to the articles in these 4 sections in the mobile application and when clicked on, the page can be redirected to the page as it appears in the web panel.

**Comment by JGeek00** [comment]
Added on v2.14.0-beta.1
