### ISSUE TITLE
Add block client option

### ISSUE THREAD

**Issue by thestablelover** [JGeek00/adguard-home-manager#99]
![Screenshot_20231211-013549_Brave.jpg](https://github.com/JGeek00/adguard-home-manager/assets/75412448/48154436-ad11-46e3-b0f5-82aba5367f87)

Add custom blocking option to each client (Home page) If added, this client will most likely be added to the access settings section.

**Comment by JGeek00** [comment]
Added on v2.14.0-beta.1
